import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, signIn, test } from "./fixtures.js";
import { E2E_VAULT, scratchNote } from "./environment.js";

test("Enter adds durable lines within an empty table cell", async ({ page }, info) => {
  await signIn(page);
  const note = scratchNote("tables-newlines", info.project.name);
  await page.goto(`/v/personal/${note}`);
  const editor = page.locator(".editor-surface .tiptap");
  await expect(editor).toContainText("A note this test may edit");
  await editor.getByText("A note this test may edit.", { exact: true }).click();
  await page.getByRole("button", { name: "Insert table block", exact: true }).click();
  const table = editor.locator("table");
  const cell = table.locator("tr").nth(1).locator("td").nth(1);
  await cell.click();
  await page.keyboard.press("Enter");
  await page.keyboard.type("Second line");
  await page.keyboard.press("Shift+Enter");
  await page.keyboard.press("Enter");
  await page.keyboard.type("Fourth line");
  await expect(table.locator("tr")).toHaveCount(3);
  await expect(cell.locator("br")).toHaveCount(3);
  for (let row = 0; row < 3; row += 1) await expect(table.locator("tr").nth(row).locator("td")).toHaveCount(2);
  await page.keyboard.press("ControlOrMeta+Enter");
  await page.keyboard.type("Shortcut row");
  await expect(table.locator("tr")).toHaveCount(4);
  await expect(table.locator("tr").nth(2)).toContainText("Shortcut row");
  await expect(table.locator("tr").nth(2).locator("td")).toHaveCount(2);
  await expect.poll(() => readFileSync(join(E2E_VAULT, note), "utf8"), { timeout: 15_000 }).toContain("<br>Second line<br><br>Fourth line");
  await expect.poll(() => readFileSync(join(E2E_VAULT, note), "utf8"), { timeout: 15_000 }).toContain("| Shortcut row |  |");
  await page.reload();
  await expect(cell.locator("br")).toHaveCount(3);
  await expect(cell).toContainText("Fourth line");
  await expect(table.locator("tr")).toHaveCount(4);
});

test("table columns stay stable as empty cells gain long text", async ({ page }, info) => {
  await signIn(page);
  await page.goto(`/v/personal/${scratchNote("tables-layout", info.project.name)}`);
  const editor = page.locator(".editor-surface .tiptap");
  await expect(editor).toContainText("A note this test may edit");
  await editor.getByText("A note this test may edit.", { exact: true }).click();
  await page.getByRole("button", { name: "Insert table block", exact: true }).click();
  const table = editor.locator("table");
  const widths = await table.locator("tr").first().locator("td").evaluateAll((cells) => cells.map((cell) => cell.getBoundingClientRect().width));
  await table.locator("tr").nth(1).locator("td").nth(1).click();
  await page.keyboard.type("A very long description ".repeat(8));
  const after = await table.locator("tr").first().locator("td").evaluateAll((cells) => cells.map((cell) => cell.getBoundingClientRect().width));
  after.forEach((width, index) => expect(Math.abs(width - (widths[index] ?? 0))).toBeLessThan(1));
  await table.locator("tr").nth(1).locator("td").first().click({ position: { x: 60, y: 20 } });
  await page.keyboard.press("Backspace");
  await expect(table.locator("tr")).toHaveCount(3);
  await expect(table.locator("tr").nth(1)).toContainText("A very long description");
  const openRow = async (row: number): Promise<void> => {
    const handle = page.getByRole("button", { name: `Move table row ${row}`, exact: true });
    if (info.project.name === "mobile") await handle.tap();
    else await handle.click();
    await expect(page.getByRole("dialog", { name: `Actions for row ${row}` })).toBeVisible();
  };
  await openRow(1);
  await page.getByRole("button", { name: "New row above", exact: true }).click();
  await expect(table.locator("tr")).toHaveCount(4);
  await expect(table.locator("tr").nth(2)).toContainText("A very long description");
  await openRow(2);
  await page.getByRole("button", { name: "New row below", exact: true }).click();
  await expect(table.locator("tr")).toHaveCount(5);
  await openRow(2);
  await page.getByRole("button", { name: "Delete row", exact: true }).click();
  await expect(table.locator("tr")).toHaveCount(4);
  await expect(table).not.toContainText("A very long description");
  await openRow(1);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "Actions for row 1" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Move table row 1", exact: true })).toBeFocused();
  await table.locator("tr").nth(1).locator("td").nth(1).click();
  await page.keyboard.press("Backspace");
  await page.keyboard.type("Left cell");
  await expect(table.locator("tr").nth(1).locator("td").first()).toContainText("Left cell");
  for (let character = 0; character < "Left cell".length; character += 1) await page.keyboard.press("Backspace");
  await page.keyboard.press("Backspace");
  await expect(table.locator("tr")).toHaveCount(3);
  for (let row = 0; row < 3; row += 1) await expect(table.locator("tr").nth(row).locator("td")).toHaveCount(2);
  await table.locator("tr").first().locator("td").first().click();
  await page.keyboard.press("Backspace");
  await expect(table.locator("tr")).toHaveCount(3);
  await openRow(1);
  await page.getByRole("button", { name: "Delete row", exact: true }).click();
  await expect(table.locator("tr")).toHaveCount(2);
  await openRow(1);
  await page.getByRole("button", { name: "Delete row", exact: true }).click();
  await expect(table).toHaveCount(0);
  await page.keyboard.type("Continue after table");
  await expect(editor).toContainText("Continue after table");
  const path = join(E2E_VAULT, scratchNote("tables-layout", info.project.name));
  await expect.poll(() => readFileSync(path, "utf8"), { timeout: 15_000 }).toContain("Continue after table");
  expect(readFileSync(path, "utf8")).not.toContain("| ---");
  await page.reload();
  await expect(editor).toContainText("Continue after table");
  await expect(editor.locator("table")).toHaveCount(0);
});

test("visual tables edit headers, grow, reorder and persist as Markdown", async ({ page }, info) => {
  await signIn(page);
  const note = scratchNote("tables", info.project.name);
  await page.goto(`/v/personal/${note}`);
  const editor = page.locator(".editor-surface .tiptap");
  await expect(editor).toContainText("A note this test may edit");
  await editor.getByText("A note this test may edit.", { exact: true }).click();
  await page.getByRole("button", { name: "Insert table block", exact: true }).click();
  const table = editor.locator("table");
  await expect(table.locator("tr")).toHaveCount(3);
  await table.locator("td").first().click();
  await page.keyboard.type("Item");
  await page.getByRole("button", { name: "Add column", exact: true }).click();
  await expect(table.locator("tr").first().locator("td")).toHaveCount(3);
  for (const [column, label] of [[1, "Status"], [2, "Notes"]] as const) {
    await table.locator("tr").nth(1).locator("td").nth(column).click();
    await page.getByRole("button", { name: "Edit header", exact: true }).click();
    await page.keyboard.type(label);
    await expect(table.locator("tr").first().locator("td").nth(column)).toHaveText(label);
  }
  await table.locator("tr").nth(1).locator("td").nth(1).click();
  await page.keyboard.type("Alpha");
  await table.locator("tr").nth(2).locator("td").nth(1).click();
  await page.keyboard.type("Beta");
  await page.getByRole("button", { name: "Row up", exact: true }).click();
  await expect(table.locator("tr").nth(1)).toContainText("Beta");
  if (info.project.name === "desktop") {
    await page.getByRole("button", { name: "Move table row 1", exact: true })
      .dragTo(table.locator("tr").nth(2).locator("td").nth(1));
    await expect(table.locator("tr").nth(1)).toContainText("Alpha");
  } else {
    const handle = await page.getByRole("button", { name: "Move table row 1", exact: true }).boundingBox();
    const target = await table.locator("tr").nth(2).locator("td").nth(1).boundingBox();
    if (handle === null || target === null) throw new Error("table drag targets are not visible");
    const session = await page.context().newCDPSession(page);
    await session.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: handle.x + handle.width / 2, y: handle.y + handle.height / 2 }] });
    await session.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: target.x + target.width / 2, y: target.y + target.height / 2 }] });
    await session.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
    await session.detach();
    await expect(table.locator("tr").nth(1)).toContainText("Alpha");
  }
  await page.getByRole("button", { name: "Add row", exact: true }).click();
  await expect(table.locator("tr")).toHaveCount(4);
  await page.getByRole("button", { name: "Edit header", exact: true }).click();
  await expect(page.getByRole("button", { name: "Row up", exact: true })).toBeDisabled();
  await expect.poll(() => readFileSync(join(E2E_VAULT, note), "utf8"), { timeout: 15_000 }).toContain("| Item |");
  await expect.poll(() => readFileSync(join(E2E_VAULT, note), "utf8"), { timeout: 15_000 }).toContain("| Item | Status | Notes |");
  await expect.poll(() => readFileSync(join(E2E_VAULT, note), "utf8"), { timeout: 15_000 }).toContain("Beta");
  await page.reload();
  await expect(editor.locator("table tr")).toHaveCount(4);
  await expect(editor.locator("table")).toContainText("Alpha");
  await expect(editor.locator("table tr").first().locator("td")).toHaveText(["Item", "Status", "Notes"]);
});
