//! Daily-note path rules (`SPEC.md` §15.1).
//!
//! This module deliberately owns only deterministic path formatting and parsing. Reading a
//! vault and deciding which dates a caller may see belongs to `mb-server`'s authorized view.

use crate::task::Date;

/// A calendar-note cadence with its own filename directives.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Period {
    /// One note per calendar day. Requires `%Y`, `%m`, and `%d`.
    Daily,
    /// One note per ISO week. Requires `%G` (week year) and `%V` (week number).
    Weekly,
    /// One note per calendar month. Requires `%Y` and `%m`.
    Monthly,
}

/// Formats a vault-relative daily-note path from a folder and a strftime-like date pattern.
///
/// The supported date directives are `%Y`, `%m`, and `%d`. A pattern must produce a Markdown
/// filename and may not escape its folder. Returns `None` for an unsafe configuration.
#[must_use]
pub fn path(folder: &str, format: &str, date: Date) -> Option<String> {
    periodic_path(Period::Daily, folder, format, date)
}

/// Formats a vault-relative calendar-note path for `period`.
#[must_use]
pub fn periodic_path(period: Period, folder: &str, format: &str, date: Date) -> Option<String> {
    let folder = valid_folder(folder)?;
    let filename = format_date(period, format, date)?;
    if !filename.ends_with(".md") || filename.is_empty() {
        return None;
    }
    let relative = format!("{folder}{filename}");
    crate::permissions::NotePath::parse(&relative).ok()?;
    Some(relative)
}

/// Parses a date from a path generated by [`path`].
#[must_use]
pub fn date_from_path(folder: &str, format: &str, note: &str) -> Option<Date> {
    periodic_date_from_path(Period::Daily, folder, format, note)
}

/// Parses the representative date from a path generated by [`periodic_path`].
///
/// Weekly paths return the Monday of their ISO week; monthly paths return the first day.
#[must_use]
pub fn periodic_date_from_path(
    period: Period,
    folder: &str,
    format: &str,
    note: &str,
) -> Option<Date> {
    let folder = valid_folder(folder)?;
    let filename = note.strip_prefix(folder)?;
    let mut input = filename;
    let mut pattern = format;
    let mut parts = DateParts::default();
    while let Some(index) = pattern.find('%') {
        let literal = &pattern[..index];
        input = input.strip_prefix(literal)?;
        pattern = &pattern[index + 1..];
        let directive = pattern.chars().next()?;
        pattern = &pattern[directive.len_utf8()..];
        let width = match directive {
            'Y' | 'G' => 4,
            'm' | 'd' | 'V' => 2,
            _ => return None,
        };
        let value = input.get(..width)?;
        if !value.bytes().all(|byte| byte.is_ascii_digit()) {
            return None;
        }
        parts.set(directive, value.parse().ok()?)?;
        input = &input[width..];
    }
    input = input.strip_prefix(pattern)?;
    if !input.is_empty() {
        return None;
    }
    parts.date(period)
}

#[derive(Default)]
struct DateParts {
    year: Option<i32>,
    month: Option<u8>,
    day: Option<u8>,
    week_year: Option<i32>,
    week: Option<u8>,
}

impl DateParts {
    fn set(&mut self, directive: char, value: i32) -> Option<()> {
        match directive {
            'Y' => set_once(&mut self.year, value),
            'G' => set_once(&mut self.week_year, value),
            'm' => set_once(&mut self.month, u8::try_from(value).ok()?),
            'd' => set_once(&mut self.day, u8::try_from(value).ok()?),
            'V' => set_once(&mut self.week, u8::try_from(value).ok()?),
            _ => None,
        }
    }

    fn date(self, period: Period) -> Option<Date> {
        match period {
            Period::Daily => Date::new(self.year?, self.month?, self.day?),
            Period::Weekly => Date::from_iso_week(self.week_year?, self.week?),
            Period::Monthly => Date::new(self.year?, self.month?, 1),
        }
    }
}

fn set_once<T: Copy + PartialEq>(slot: &mut Option<T>, value: T) -> Option<()> {
    match slot {
        Some(existing) if *existing != value => None,
        Some(_) => Some(()),
        None => {
            *slot = Some(value);
            Some(())
        }
    }
}

fn valid_folder(folder: &str) -> Option<&str> {
    if folder.is_empty() {
        return Some("");
    }
    if !folder.ends_with('/')
        || folder.starts_with('/')
        || folder
            .trim_end_matches('/')
            .split('/')
            .any(|part| part.is_empty() || part == "." || part == ".." || part.starts_with('.'))
    {
        return None;
    }
    Some(folder)
}

fn format_date(period: Period, format: &str, date: Date) -> Option<String> {
    let mut output = String::new();
    let mut rest = format;
    let (iso_year, iso_week) = date.iso_week();
    let mut seen_year = false;
    let mut seen_month = false;
    let mut seen_day = false;
    let mut seen_week_year = false;
    let mut seen_week = false;
    while let Some(index) = rest.find('%') {
        output.push_str(&rest[..index]);
        rest = &rest[index + 1..];
        let directive = rest.chars().next()?;
        rest = &rest[directive.len_utf8()..];
        match directive {
            'Y' => {
                seen_year = true;
                output.push_str(&format!("{:04}", date.year()));
            }
            'm' => {
                seen_month = true;
                output.push_str(&format!("{:02}", date.month()));
            }
            'd' => {
                seen_day = true;
                output.push_str(&format!("{:02}", date.day()));
            }
            'G' => {
                seen_week_year = true;
                output.push_str(&format!("{iso_year:04}"));
            }
            'V' => {
                seen_week = true;
                output.push_str(&format!("{iso_week:02}"));
            }
            _ => return None,
        }
    }
    output.push_str(rest);
    match period {
        Period::Daily if seen_year && seen_month && seen_day => Some(output),
        Period::Weekly if seen_week_year && seen_week => Some(output),
        Period::Monthly if seen_year && seen_month => Some(output),
        _ => None,
    }
}
